### ISSUE TITLE
Reference overlapping documentation between client website and design system website

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#108]
## Description
While completing work for ticket #106 we discovered there may be some overlap between the client website and the design system website. Specifically, https://design.va.gov/patterns/ includes guidance on how a form introduction page should be laid out, how labels and errors messages should be phrased, and several other things. [The form features and usage guidelines section](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines) on the client site includes similar information on some of the same topics.

## Tasks
- Analyze overlaps between [form features and usage guidelines](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines) and [design system patterns](https://design.va.gov/patterns/)
- Reference relevant content on the [form features and usage guidelines](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/available-features-and-usage-guidelines) and [design system patterns](https://design.va.gov/patterns/) from the appropriate pages in the new [VA Forms Library help section](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html).

### Design Documentation to reference
- [Form feedback messaging](https://design.va.gov/patterns/messaging-dictionary#feedback-messaging)
- [Form confirmation page](https://design.va.gov/patterns/form-confirmation-page)
- [Form Error messaging guidance](https://design.va.gov/patterns/form-feedback)
- [Form label master list](https://design.va.gov/patterns/form-labels)
- [Form field patterns](https://design.va.gov/patterns/form-patterns)
- [Utility classes](https://design.va.gov/utilities/)

**NOTE: WORK ON TICKET 157 MAY RESULT IN A DECISION TO DEPRECATE/REMOVE THE CURRENT CLIENT APPLICATION DOCUMENTATION CONTENT FOR FORMS (https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/). WITH THAT IN MIND, WE SHOULD PROBABLY REFERENCE CONTENT FROM THE DESIGN SYSTEM WEBSITE ONLY.**

Section on the Overview page that provides links to design system utility classes and form patterns pages.

## Acceptance Criteria
- [x] References to content in the two areas referenced above have been added to the appropriate pages in the new [VA Forms Library help section](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html).
- [x] A list of pages pages in the new [VA Forms Library help section](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html) that were updated with references to content in the two areas referenced above is included as a comment on this ticket so that we know what changes were made at this time.

**Comment by micahchiang** [comment]
[Change is staged](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2085355587/VA+Forms+Library+Overview), moving to ready for review until it gets published.

**Comment by taylorkaren** [comment]
Updated page has been posted to the live site: https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html.
