### ISSUE TITLE
Documentation Work: schema and uiSchema

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#120]
## Description
Schema and uiSchema are the building blocks for forms on VA.gov. While `schema` is relatively self explanatory, there are many arcane properties and attributes a user can leverage on `uiSchema`. This ticket should document every option available on uiSchema, what it does, and how it's used in forms in production.

**Komes to develop content, Susanna to be the FLT reviewer**

## Considerations
- [current documentation around schema and uiSchema](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects)
- Updated documentation should include: 
    - thorough descriptions of each property
    - links to examples where properties are being used in vets-website
    - optional screen captures of what attributes look like in the browser

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## Acceptance Criteria 
- [x] schema and uiSchema draft content has been written. (https://vfs.atlassian.net/wiki/spaces/FLT/pages/2104623233/VA+Forms+System+-+schema+and+uiSchema)
- [x] FLT members have reviewed and provided feedback on the draft content:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [x] Feedback has been addressed.
- [x] schema and uiSchema content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [x] schema and uiSchema content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html). (https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---schema-and-uiSchema.2104623233.html#schema-object-properties)

**Comment by micahchiang** [comment]
LGTM @kkomes! Great job.

**Comment by bjmccotter7192** [comment]
LGTM! I added a small comment about setting the language for each code snippet but otherwise good work!
