### ISSUE TITLE
Add accessibility & VAOS findings to Confluence

### ISSUE THREAD

**Issue by biannuz** [department-of-veterans-affairs/va-forms-system-core#152]
- [x] Conduct analysis on accessibility & VAOS interviews from last week & this week
- [x] Include additional documentation and references like accessibility audits & artifacts
- [x] Write up findings in Confluence page
- [x] Create specific guidance on how to make the Forms Library "accessible by default"
- [x] Note specific shortcomings preventing the current Forms Library from being accessible by default.

LINK: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2069495835/Forms+Library+Team+FLT+Early+Research+Findings#Appendix-A%3A-VAOS-Research

## This is done when...
- [x] Confluence page has been published.
- [x] FLT members have reviewed and provided feedback on the findings:
    - [x] BJ
    - [x] Karen
    - [x] Komes
    - [x] Micah
    - [x] Susanna
- [ ] Feedback has been addressed.

**Comment by biannuz** [comment]
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2069495835/Forms+Library+Team+FLT+Early+Research+Findings#Appendix-A%3A-VAOS-Research

**Comment by micahchiang** [comment]
Looks great @biannuz!

**Comment by taylorkaren** [comment]
"Initialize text" follow-up needed, then this is good to go.
