### ISSUE TITLE
Documentation Work: schema and uiSchema Part 2

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#162]
**THIS IS FOLLOW UP WORK TO THE ORIGINAL SCHEMA AND UI SCHEMA TICKET (#120) TO ADD ADDITIONAL OPTIONS TO THE PAGE CREATED FOR TICKET #120**

## Description
Schema and uiSchema are the building blocks for forms on VA.gov. While `schema` is relatively self explanatory, there are many arcane properties and attributes a user can leverage on `uiSchema`. This ticket should document every option available on uiSchema, what it does, and how it's used in forms in production.

## Considerations
- [current documentation around schema and uiSchema](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/about-the-schema-and-uischema-objects)
- Updated documentation should include: 
    - thorough descriptions of each property
    - links to examples where properties are being used in vets-website
    - optional screen captures of what attributes look like in the browser

Identify cleanup work and write a ticket to address any of these after the work on this ticket is complete:
- What outdated help information can be removed after updated information is posted to the new site?
- What outdated information should remain, but point to the new site after updated information is posted there?
- Potential outdated information areas:
-- https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/
-- Documentation listed on ticket #95: Analyze additional documentation sources and requests

## Acceptance Criteria 
- [ ] Additional schema and uiSchema draft content has been written.
- [ ] FLT members have reviewed and provided feedback on the draft content:
    - [ ] BJ
    - [ ] Harshil
    - [ ] Karen
    - [ ] Lauren
    - [ ] Micah
    - [ ] Nick
    - [ ] Susanna
- [ ] Feedback has been addressed.
- [ ] Additional schema and uiSchema content has been posted to the [Draft VA Platform Documentation site](https://vfs.atlassian.net/wiki/spaces/PWD/overview?homepageId=2018246980).
- [ ] Additional schema and uiSchema content has been posted to the [VA Platform Documentation site](https://depo-platform-documentation.scrollhelp.site/index.html).

**Comment by micahchiang** [comment]
@taylorkaren - Closing this ticket. Both @nickjg231 and I took a look through the schema and uiSchema page and feel as though it's already complete. Not much else to add at this point in time.
