### ISSUE TITLE
(Mob Session - 3/23) Establish a routing architecture for Formulate going forward

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#168]
## Description
A core piece of any multi-paged form is navigation. Specifically, route management should handle going back and forth through pages, maintaining form data that has already been filled out, and updating form state when a change occur. 

## Considerations
- Formulate already has a [bare bones router](https://github.com/department-of-veterans-affairs/formulate/blob/eb6f88dd5343d13d7e2cf3ed11732f8984731bf9/src/routing/Router.tsx#L10) setup.
- How should routing be made available to developers in vets-website? Should it still be configuration based? Should the Router just be exposed directly? 
 - [Existing tickets for Formulate routing](https://github.com/department-of-veterans-affairs/va-forms-system-core/projects/2):
    - Look at the open ones, figure out which of those we should bring over to our board, and move them. - DONE
    - Look at the closed ones, figure out if any of the work on those tickets will need to be redone or can be used as is. DONE
- [Existing Formulate Routing Epic](https://github.com/department-of-veterans-affairs/va.gov-team/issues/25665):  - Add anything from this to our Routing epic ticket (https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/180)? 
    - Can close the existing ticket if we have everything we need on our Routing epic ticket.
 - Review [URLs for the form should be able to support route parameters #33328](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/33328) and bring this ticket over to our board or close if applicable.
 - Review [Fix deprecated route syntax generated by form system](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35469) to make sure the routing approach we take will be compatible with the React upgrade referenced on this ticket. Bring this ticket over to our board or close if applicable.
## Tasks
- A decision document should be added to confluence that outlines the decision made, the approach taken, why it was chosen, and what we did about the tickets listed above. 

## Acceptance Criteria
- [x] All considerations have been addressed.
- [x] Task has been completed.

**Comment by taylorkaren** [comment]
Mob session notes: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2127200257/Mob+Session+3+16+2022+VA+Forms+Systems+Core+Routing+Architecture
Routing decision doc: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2126282811/VA+Forms+System+Core+Routing+Architecture
