### ISSUE TITLE
Research Review Page Pattern

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#170]
## Task Description
- Review existing documentation and research on the current Review Page pattern.
    - Current form pattern: https://design.va.gov/patterns/form-patterns#review-section
    - Brittany and/or Lauryl can help with finding other research
    - [Sketch for Teams file](https://www.sketch.com/s/09640425-48be-4019-8277-8a924eff1df7/a/m1GdVMk) - get credentials to view from Lauryl. Unclear as of 3/18/22 if the "VA-form-review page - current Copy" screens are really meant to correspond with what is currently in production or if these are for revisions to what is currently in production. Matt is planning to connect with Ryan to get clarification on this.
    - Also suggest talking to Natalie Hill on the Design System Team; she did a review page spec for a specific form via work on this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31164
- Summarize findings on a Confluence page.

## Considerations
- Goal is to understand the research that has been done and use this understanding as a foundation for developing a spec for a new review page pattern.
    - In general, the review page has accessibility issues, a poor UI pattern (e.g., expandable tabs), and can get long for forms that collect a large amount of data.
- The uk.gov summary page pattern has been a popular reference when talking about the review page (https://design-system.service.gov.uk/components/summary-list/). We should look at what is there, but we should not do something just because uk.gov does it.
 - Open ticket for a spec: https://github.com/department-of-veterans-affairs/va.gov-team/issues/31164 (move to our repository or close this ticket and create our own spec ticket?)
 - Open ticket requesting a Customizable Review Page: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12808 (we can choose to incorporate this or not)
 - Open ticket about unwanted saving functionality on the current review page: https://github.com/department-of-veterans-affairs/va.gov-team/issues/35723
 - Open ticket about displaying an array of items on the review page: https://github.com/department-of-veterans-affairs/va.gov-team/issues/34828 (this ticket needs clarification - title says it's a bug, but the description sounds more like a feature request and it looks like there might be a general forms page request here in addition to the review page request).

## This is done when
 - Research findings and conclusions are summarized on a Confluence page in the Discovery section of the FLT space.

**Comment by taylorkaren** [comment]
Hey @KavithaKrishnan I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by KavithaKrishnan** [comment]
Link to the [Confluence page](https://vfs.atlassian.net/l/c/H8bB1S4b)
