### ISSUE TITLE
Documentation Work: Fix intrapage links on the Form Config and schema pages

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#183]
## Task Description
Find and fix all intrapage links on these pages so that they correctly navigate to the appropriate section on the page:
- [VA Forms System - Form Config Options help page](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---Form-Config-Options.2097381477.html) (NOTE that this may be resolved by work Komes did before he left. Please review the page to confirm all links are fixed.)
- [VA Forms System - schema and uiSchema](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---schema-and-uiSchema.2104623233.html#schema-object-properties)

## Problem Statement
- Links on the pages listed above to other sections on the same page are not working.
    - Example: Selecting the savedFormMessages links in the form configurations table at the top of the [VA Forms System - Form Config Options help page](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System---Form-Config-Options.2097381477.html) does not navigate to the savedFormMessages section lower on the page. 

## Acceptance Criteria
- All intrapage links on the pages listed above correctly navigate to the appropriate section on the page.

**Comment by bjmccotter7192** [comment]
Got all the links updated and added anchors to the missing links in the uiSchema and Schema documents and got both moved back to the Platform Documentation site.

**Comment by taylorkaren** [comment]
Reviewed the Form Config page - fixed a couple of typos in the intrapage links and added JavaScript as the language for all code snippets. Published changes so that they will go to prod next time there is a site deploy.

**Comment by taylorkaren** [comment]
Reviewed the schema and uiSchema page - fixed a few formatting issues and changed VAFS references to Forms Library. Published changes so that they will go to prod next time there is a site deploy.
