### ISSUE TITLE
Widget research

### ISSUE THREAD

**Issue by biannuz** [department-of-veterans-affairs/va-forms-system-core#189]
Conduct secondary research (with some primary as needed) to answer the following:

- [ ] What widgets/form elements do engineers use the most? (e.g. full name, address, etc.) (We're waiting to hear back from Platform Analytics about stats - I will join their office hours on Tuesday if I don't hear back by then.)
- [ ] Pending a list from Carol Wong.
- [ ] Which widgets work best/are most reliable?
- [x] Which widgets cause the most issues?
- [ ] Message Paul Smith with a link to the research page when it is complete. This is the [Slack thread](https://adhoc.slack.com/archives/C9N13SSCQ/p1649446685625099) for the relevant conversation.

## Acceptance Criteria
- [x] Draft content has been written.
- [x] FLT members have reviewed and provided feedback on [the draft content:](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2161836319/Widget+Research)
    - [x] BJ
    - [x] Harshil
    - [x] Karen
    - [x] Lauren
    - [x] Micah
    - [x] Nick
    - [x] Susanna
- [ ] Feedback has been addressed.

**Comment by biannuz** [comment]
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2161836319/Widget+Research

**Comment by bjmccotter7192** [comment]
LGTM

**Comment by micahchiang** [comment]
LGTM, thanks @biannuz!
