### ISSUE TITLE
Q1 metrics follow-up Part 1: Jan - April 2022 Stats

### ISSUE THREAD

**Issue by biannuz** [department-of-veterans-affairs/va-forms-system-core#190]
## Task Description
- Compile Jan - April 2022 stats on Forms Library support requests logged in the #vfs-platform-support channel.
- This will give us the snapshot of metrics before the updated Forms Library documentation was available in the [VA Forms Library section of the Developer Docs Platform Website](https://depo-platform-documentation.scrollhelp.site/developer-docs/VA-Forms-System-Overview.2085355587.html).

## Considerations
- Source doc is the [Platform Support Responses sheet](https://docs.google.com/spreadsheets/d/1TItdfPMH_TiXEhgMKEqxIW2e5EaMKy4cHaBhaeQ7drU/edit#gid=0).
- Use the [Q1 metrics page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2051538980/Q1+2022+Baseline+KRs) as guidance to derive the same stats, based on platform-support channel requests, for the mid-January to mid-April 2022 time frame so that we can see what the support requests related to Forms Library looked like during the quarter before the new docs were available.
- We will eventually compare these metrics to the metrics for the first quarter after the new documentation was available (ticket #246) to determine if the updated documentation had any impact in the number and nature of Forms Library support requests.
- **NOTE** that the Forms Library Team took over support for the Forms Library as of 4/14/22, so requests after that date will be coded with Forms Library as the Topic, rather than Design System.

## Acceptance Criteria
- Create a document in Confluence, similar to the [Q1 metrics page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2051538980/Q1+2022+Baseline+KRs), that includes the same data for Forms Library support requests during the January 20, 2022 - April 20, 2022 time frame.

**Comment by taylorkaren** [comment]
Document: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2256273409/Q2+2022+Forms+Library+KRs+January+-+April+2022+Stats+before+updated+documentation.

**Comment by taylorkaren** [comment]
Reviewed updates - good to go!
