### ISSUE TITLE
Forms library: [Routing] Create form-wide layout elements

### ISSUE THREAD

**Issue by caw310** [department-of-veterans-affairs/va-forms-system-core#197]
## Description
Forms on VA.gov should provide a uniform experience; the form name, description, and footer should be consistent throughout. This is categorized as part of routing because the `Router` component will handle the rendering for the aforementioned elements, which could look something like this:

```
export default function Router(props: RouterProps): JSX.Element {
  return (
    <BrowserRouter basename={props.basename}>
      <FormHeader title={props.someTitle} description={props.someDescription} />
      <Switch>{props.children}</Switch>
      <FormFooter content={props.footerContent} />
    </BrowserRouter>
  );
}
```
<details><summary>Current Form Header and Footer</summary>

![Screen Shot 2022-03-29 at 3.37.32 PM.png](https://images.zenhubusercontent.com/5d68043b330f64311395e92b/31eae984-eddb-445e-bdbf-09450e028821)
</details>

## Considerations
- [Current form title component](https://github.com/department-of-veterans-affairs/vets-website/blob/150a9867939b011ab385b908fa54cae67dd12ec0/src/platform/forms-system/src/js/components/FormTitle.jsx#L3) can most likely be duplicated

**Comment by taylorkaren** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/282.
