### ISSUE TITLE
Identify accessibility issues in the Review page and provide solution

### ISSUE THREAD

**Issue by KavithaKrishnan** [department-of-veterans-affairs/va-forms-system-core#223]
4/8/22: There was a course change on this ticket:
- Kavitha started looking for issues related to the current Review Page before we decided to go with a limited functionality version of a new review page pattern for the Q2 working demo.
- Result of that effort is that we identified accessibility issues specific to the old pattern, most of which are probably not applicable to the work we will be doing on a new pattern, and some additional issues - these are in the [Research for 223 document](https://docs.google.com/document/d/1djHugik_kKItaxmq_6dQfIEBXztOmWsZc0RkUNFLWnY/edit#).
- We were also looking into accessibility issues related to forms in general for ticket #192, so that Micah and Katy could work on prioritizing what makes sense to address in the current Forms Library and what makes sense to address from the ground up in the new Forms System Core.
- This resulted in some of the entries in the [Research for 223 document](https://docs.google.com/document/d/1djHugik_kKItaxmq_6dQfIEBXztOmWsZc0RkUNFLWnY/edit#), a [Micah list](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/board?labels=508%2Faccessibility,forms&repos=133843125,152664242,194202180), and a [Karen list](https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams#workspaces/vsp-5cedc9cce6e3335dc5a49fc4/board?labels=508%2Faccessibility,forms&repos=133843125) of forms accessibility issues.
- Karen combined these lists into a [super set list of forms accessibility issues](https://docs.google.com/spreadsheets/d/1M9wfqjLNjecPvwhl8XmJxBJi2CbiOyRS-_9uI3Dn678/edit#gid=0), with some analysis and first cut recommendations about what could be prioritized. This will be what we use for moving forward with Ticket #192.
- Meeting set for 4/11 for Karen, Micah, and Kavitha to review the [super set list of forms accessibility issues](https://docs.google.com/spreadsheets/d/1M9wfqjLNjecPvwhl8XmJxBJi2CbiOyRS-_9uI3Dn678/edit#gid=0) and plan for the meeting with Katy to prioritize and determine what DST and FLT will take on.

=====================================================
## Task Description
- Based on the research for Review page pattern #170, clearly list accessibility issues in the Review page and potential solutions to implement. 
- Should include general good accessibility practices such as making sure all buttons, links and headers are labeled for screen reader accessibility, and any specific findings related to the Review Page.

## Ticket 170 work product references
- Zenhub link - https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/170
- Confluence link - https://vfs.atlassian.net/l/c/H8bB1S4b

## Resources
- ZenHub board filtered for 508 and forms labels (not all of these will be Review Page): https://github.com/department-of-veterans-affairs/va.gov-team/tree/master/teams#workspaces/vsp-5cedc9cce6e3335dc5a49fc4/board?labels=508%2Faccessibility,forms&repos=133843125
- Kavitha's analysis doc in progress: https://docs.google.com/document/d/1djHugik_kKItaxmq_6dQfIEBXztOmWsZc0RkUNFLWnY/edit.

## Acceptance Criteria
- [ ]  Summarize accessibility issues and solutions on a Confluence page, to be used as the basis for additional ticket(s) for the Q2 Working Demo Review Page build work.

**Comment by taylorkaren** [comment]
Superset of accessibility issues: https://docs.google.com/spreadsheets/d/1M9wfqjLNjecPvwhl8XmJxBJi2CbiOyRS-_9uI3Dn678/edit#gid=0).
