### ISSUE TITLE
Fix Date Field errors

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va-forms-system-core#247]
Date field has a bug and is causing validation hook errors in Formik. 

![Screen Shot 2022-04-14 at 5.23.51 PM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/d9f099b8-e167-4e1a-a331-b9cb0be70eab)

**Comment by micahchiang** [comment]
Closing in favor of #220
