### ISSUE TITLE
Widget research part 2

### ISSUE THREAD

**Issue by biannuz** [department-of-veterans-affairs/va-forms-system-core#262]
Conduct primary research to determine:

- [ ] What widgets/form elements do engineers use the most? (e.g. full name, address, etc.)
- [ ] In their experience, which widgets work best/are most reliable?
- [ ] Which widgets are least reliable?
- [ ] Message Paul Smith with a link to the research page when it is complete. This is the [Slack thread](https://adhoc.slack.com/archives/C9N13SSCQ/p1649446685625099) for the relevant conversation.

Methodology: A short (5-10 minutes) questionnaire for engineers with experience using the forms library to complete in their own time.

**Comment by micahchiang** [comment]
WON'T FIX
