### ISSUE TITLE
(ADD AC) [Q2 Demo Prep] Clean up the examples directory in the va-forms-system core repository

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#270]
## Task Description
- Clean up the [examples directory](https://github.com/department-of-veterans-affairs/va-forms-system-core/tree/master/examples) in the va-forms-system core repository.
 - Focus on including all examples in the [multipage form](https://github.com/department-of-veterans-affairs/va-forms-system-core/tree/master/examples/multipage-form) and remove the other examples.
- This multipage form will be the starting point for the Q2 Working Demo model form that we will build via ticket #259.

## Acceptance Criteria
[TO BE ADDED]

**Comment by micahchiang** [comment]
done when we upgraded to react router v6
