### ISSUE TITLE
508-defect-4 – Consider adding a `name` attribute to all our benefit applications' `form` elements 

### ISSUE THREAD

**Issue by erikphansen** [department-of-veterans-affairs/va-forms-system-core#285]
[This PR](https://github.com/department-of-veterans-affairs/vets-website/pull/13256) added support for optionally using a `SchemaForm`'s `name` prop as the rendered `<form>`'s `name` attribute. Using a name attribute on a `form` enables the element's implicit form role. From https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form:

> **Implicit ARIA role:** `form` if the form has an accessible name, otherwise no corresponding role

If we flipped the default value of `addNameAttribute` from `false` to `true` then all `form` elements rendered by the Form System would have an implicit `role="form"` (yay!) but the `name` attribute for each `form` would be camelCase which is ugly and might introduce a new a11y concern.

**Comment by taylorkaren** [comment]
@obliviga: Please note that the work for this ticket is only for the new VAFSC core application, it is not retrofitting anything in the current Forms Library. If you want to stay focused on current Forms Library work, OK to remove the sprint assignment from this ticket and put it back in the Accessibility Fixes pipeline.

**Comment by obliviga** [comment]
After doing more research into this, I've discovered that the name attribute's purpose on the form element is to make the form available to the `document.forms` API. So we would be able to access the form by running `document.formName`.

If we need to select the form currently, we could simply use `getElementById` or some other method to query the document. So unless we plan to use the `document.forms` API, I think this ticket can be closed.

[Source](https://www.w3.org/TR/2021/SPSD-html52-20210128/sec-forms.html#the-form-element)

cc @micahchiang @taylorkaren
