### ISSUE TITLE
React Router 3 --> 5 - Cross Teams

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#287]
## Background Information
React Router 6 has already been implemented for the new VA Forms System Core; this ticket will track effort by the Forms Library Team to work with other relevant VA teams to make that same update for the VA in general.

## Work done to date
Looks like there are three tickets related to this work:
- [Upgrade react-router from v3 to v5.1.2#34572](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/34572): Ticket covering upgrading from v3 to v5.1.2. 
- [Update form routers to be compatible with v5#36088](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/36088): This is an Open ticket to address updating route definitions for the forms listed on the ticket.
- [Fix deprecated route syntax generated by form system #35469](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35469): **_Open ticket to...make sure everything works with v5.1.2??_**

And one documentation page:
- [React Router Guidelines](https://vfs.atlassian.net/wiki/spaces/pilot/pages/2071363787/React+Router+Guidelines): Reference information on best practices for "realizing consistent, optimal router usage across all VFS apps. They’re also useful when upgrading an app from a previous version of react-router."

## Considerations
- This work will be needed if the Q3 pilot form will be on vets-website.
- FLT to start work and be in contact with the Release Tools Team (fka Front End Tools Team) and the Design System Team to get a draft PR up and start a conversation about addressing the migration from React Router 3 --> 5, then from 5 --> 6.
- Make sure we have a rollback plan in case there are unanticipated problems when the updated code is deployed.

## Task Description
**_This needs clarification. The [Fix deprecated route syntax generated by form system #35469](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35469) ticket appears to be about finishing work to make existing forms compatible with version 5.1.2, but in the 5/4/22 refinement meeting the conversation was about working on an upgrade to v6._**

Micah to drop a message in the FE Slack channel as a first step for taking action on this ticket.

## Acceptance Criteria
- [ ] Per conversion with Matt Dingee in the 7/15/22 PO Sync call, write a short post-mortem document in Confluence summarizing the work that was done on this and why we decided to not complete it. Include a link to the draft PR for reference.

**Comment by bjmccotter7192** [comment]
Created this document to help me map what needs updating inside of vets-website since there is multiple apps already using v5 compared to the majority still using v3.
[Vets-Website React Router Upgrade v3 -> v5](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2196701189/Vets-Website+React+Router+Upgrade)

**Comment by taylorkaren** [comment]
Related to #371.

**Comment by bjmccotter7192** [comment]
Quick Post Mortem document would be cool to get a review on this and make sure I didn't miss anything.
[React Router V3 -> V5 Post Mortem](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2274263772/React+Router+V3+-+V5+Post+Mortem)
@micahchiang @taylorkaren

**Comment by taylorkaren** [comment]
Also added a comment to the following tickets noting that the Forms Library Team is no longer working on a React Router V5 - V6 upgrade with a short explanation and links to the [2022-07-15 PO Check in with Matt meeting notes](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2273378362/2022-07-15+PO+Check+in+with+Matt) and the [React Router V3 - V5 Post Mortem Confluence page]( https://vfs.atlassian.net/wiki/spaces/FLT/pages/2274263772/React+Router+V3+-+V5+Post+Mortem):
- [Upgrade react-router from v3 to v5.1.2](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/34572)
- [Fix deprecated route syntax generated by form system](https://github.com/department-of-veterans-affairs/va.gov-team/issues/35469)
- [Update form routers to be compatible with v5](https://app.zenhub.com/workspaces/vsp---release-tools-fe-5fc9325744944e0015ed1861/issues/department-of-veterans-affairs/va.gov-team/36088)

**Comment by micahchiang** [comment]
Reviewed the postmortem and it looks good to me. Thanks for writing that up @bjmccotter7192. Closing this ticket.
