### ISSUE TITLE
Remove index page from route navigation

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va-forms-system-core#366]
Currently, the route progress bar is showing up on the introduction page. This should be removed so the progress bar does not show up on the introduction page.

![Screen Shot 2022-06-03 at 9.06.13 AM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/bf303a54-c166-4176-a5d7-4bee61d4df55)

**Comment by nickjg231** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/385
