### ISSUE TITLE
Construct the list of routes

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/va-forms-system-core#37]
## Description
The `Router` needs to know what page we're currently on, what page came before, and what page comes next. To do this, we have to construct the list of routes.

## Possible implementation
- Create a `getRoutes` function on both `Page` and `Chapters`
  - `Page` returns an array with the one value for the `path`
  - `Chapter` returns an array of all the `path`s of its children (by calling `getRoutes` on them)
- Iterate over the `Router`'s children and call the `getRoutes` function on each to assemble the list

## Considerations
- React-router v6 includes a helper API called [createRoutesFromChildren](https://reactrouter.com/docs/en/v6/api#createroutesfromchildren) that may offer a solution for us.

## Acceptance criteria
- [ ] The `Router` constructs a list of routes based on its children's `path`s
- [ ] The `Router` does _not_ add `Route` `path`s to the list
    - `Route`s are pages that aren't included in the "normal" form flow, such as `/error` or `/form-saved`

**Comment by mlauren** [comment]
@taylorkaren @micahchiang this is moving in to the backlog in favor of creating a manual forward and backwards pages and refactoring the Chapter component
