### ISSUE TITLE
Forms System - Styling Components

### ISSUE THREAD

**Issue by mlauren** [department-of-veterans-affairs/va-forms-system-core#390]
- ~~Currently, the vets-website includes styling for a currency input. This should be added to the forms library.
![Screen Shot 2022-06-13 at 9.42.32 PM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/1bda3593-36fe-410b-a942-bde27c0c1cc5)~~  - Fix confirmed, 6/16

- ~~Fix styling for “On This Page” Component - no wrapping on desktop~~ - Karen posted something about this in the support channel for the Design System Team, as it is a component issue:  https://dsva.slack.com/archives/CBU0KDSB1/p1655320357706879. The Design System Team created a ticket to address this: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/951.

**Comment by taylorkaren** [comment]
For the "On this page" component, please add a comment about the fix that should be done to the component (BJ was looking at this in Storybook yesterday and had some idea about what needed to be done. We can then put a support request in with the Design System Team to look at this.

**Comment by bjmccotter7192** [comment]
When looking into the web-component here: [Link to Storybook](https://design.va.gov/storybook/?path=/story/components-va-on-this-page--default) 

I went into the `Canvas` link, then switched the `small` view to the `large` view (This is referring to the screen size) and the `OnThisPage` component seems to not change width with the page. Also looks like the words still wrap even when you have a ton of space.

**Comment by taylorkaren** [comment]
On this page component issue reported to the Design System Team on this Slack post: https://dsva.slack.com/archives/CBU0KDSB1/p1655320357706879.
