### ISSUE TITLE
Store label in state for RadioGroup Component

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va-forms-system-core#419]
## Description
We want to store a label in formik state so we can show on review page.

**Proposed solution:**
Example:
"relationship": {
        "type": "",     // Value in camel case 
        "label": "",     // Show on review page
        "other": ""     // Please specify text
}

**Comment by micahchiang** [comment]
https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/453
