### ISSUE TITLE
Direct Deposit Component - follow up for figure + figcapture pattern on the check image

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#422]
## Task Description
From Matt's comment on ticket #255:
- Update the documentation here: https://design.va.gov/patterns/forms/direct-deposit. 
    - Put together a PR that updates the image and guidance text and tag Matt to review and approve that PR.
- There are at least 2 instances of Direct Deposit: VA Profile (Samara is the PO) and Education Benefits (Accenture team). 
    - Draft text to send about the updated pattern and/or file issues for them to update the interface (it's then up to them to adopt the change) and send to Matt for review.

**Comment by obliviga** [comment]
Hi @humancompanion-usds, I've created the PR to update the documentation: https://github.com/department-of-veterans-affairs/vets-design-system-documentation/pull/999

**Comment by obliviga** [comment]
@taylorkaren I've verified that the code has been deployed to [prod](https://design.va.gov/patterns/forms/direct-deposit):

![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/7b97ea06-3bfc-41e2-a6bc-d9841ce1ba91)
