### ISSUE TITLE
Review and update VAFSC automated docs site

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#431]
## Task Description
Review the VA Forms System Docs site at https://department-of-veterans-affairs.github.io/va-forms-system-core/ and:
- Make sure all documentation on the site is current and up to date with the current state of the VAFSC.
- Remove any documentation that is outdated
- Consider the usefulness of the content currently in the Explanations, How To Guides, and Tutorials sections and revise or remove as applicable.
- Make sure all of this is up to date and remove the Beta tags: https://department-of-veterans-affairs.github.io/va-forms-system-core/reference/va-forms-system-core.

## Acceptance Criteria
- [x] Tasks have been completed.
- [x] Comment on this ticket summarizing the updates made to the documentation site.

**Comment by micahchiang** [comment]
Update some of the release tags from beta to public. Also update some of them from beta to internal.
