### ISSUE TITLE
Field: Link

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#436]
## Task Description
- Evaluate if any work is needed to use the Link web component in the VAFSC.
- If work is needed to use the Link web component in the VAFSC...**_add tasks to be done._**
- If work is not needed to use the Link web component in the VAFSC, update the Link entry on the [VAFSC Web Components - Tracking Page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2142863361/VAFSC+Web+Components+-+Tracking+Page): 
    - Change the "In the VAFSC" entry from No to Yes
    - Replace the current Notes column text with "There isn't anything that needs to be done within VAFSC to use this, as it just manages static content. If an engineer wishes to incorporate this into one of their form page components, they would just use it inline."

## Considerations
- Design System web component documentation: https://design.va.gov/components/link/
    - Status here says Deployed
- Storybook link: https://design.va.gov/storybook/?path=/docs/components-va-link--default
    - Status here says Use with Caution: Candidate
- For non-navigation links.

## Acceptance Criteria
- [ ] If work is needed to use the Link web component in VAFSC...**_add AC items_** 
- [x] If work is not needed to use the Link web component in VAFSC, the Link entry on the [VAFSC Web Components - Tracking Page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2142863361/VAFSC+Web+Components+-+Tracking+Page) has been updated as described above in the Task Description section.

**Comment by obliviga** [comment]
If we want to use the VaLink component in VAFCS, then we should be able to import it like `import { VaLink } from '@department-of-veterans-affairs/component-library/dist/react-bindings';`

I don't think any work is needed here, but will get a second pair of eyes to confirm just in case.

**Comment by obliviga** [comment]
I've updated the documentation to include that work is not needed to use the Link web component in the VAFSC.
