### ISSUE TITLE
Add a prop to populate a fieldset legend tag in the VAFSC full name and address fields

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#438]
Split off from this original ticket to document the work to be done for VAFSC; DST will do the work in the current system on this original ticket: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/284.

## Task Description
Update the full name and address fields in the new VAFSC components to optionally accept a prop that populates a fieldset legend tag.
Add info about this new prop to the documentation for these components.

## Considerations
This update is ONLY for VAFSC. The Design System Team is planning to work on the original ticket for changes to the existing system.

## Acceptance Criteria
- [x] Ensure that the `FullNameField` and `AddressField` components have props that allows engineers to toggle and customize associated `fieldset` and `legend` elements

**Comment by obliviga** [comment]
This feature has been successfully deployed to the main branch:
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/b570d940-8b65-490b-898e-193aa2ada918)
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/bf470297-0a6c-4e8f-8c07-c80699e89fbd)
