### ISSUE TITLE
sitewide, forms 508-defect-2 [AXE-CORE]: Heading levels SHOULD increase by one

### ISSUE THREAD

**Issue by jenstrickland** [department-of-veterans-affairs/va-forms-system-core#439]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

**Feedback framework**
- **❗️ Must** for if the feedback must be applied 
- **⚠️Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

The alert box heading, "Save time—and save your work in progress—by signing in before starting your application," is currently an h3 but there isn't an h2 between it and the h1. 

* If this page is in the CMS, it is a CMS sitewide issue. If this is a CMS page, please comment on this ticket, letting me know who your CMS partner is, and I will reassign.

* If this page is built in React, there is a level prop that needs to be adjusted to "2", and a utility class will style it to look like an h3.

## Point of Contact

**VFS Point of Contact:** Jennifer

## Acceptance Criteria

As a screen reader user, I want to navigate the hierarchy of the page content using heading levels to save time and frustration.

## Environment

- Operating System: all
- Browser: all
- Screenreading device: any
- Server destination: staging & production

## Steps to Recreate

1. Enter [URL] in browser
2. Have developer tools open, and the axe browser extension loaded
3. Run an axe audit
4. Verify that [heading code] is called out as an error of "Heading levels should only increase by one"
5. This error is repeated throughout the form process

### Sample 

**Current code**
```html
<h3 class="usa-alert-heading">Save time—and save your work in progress—by signing in before starting your application</h3>
```

**Recommended code**
```html
<h2 class="usa-alert-heading">Save time—and save your work in progress—by signing in before starting your application</h2>
```

```diff
! Team impacted: BAM1; Project: BDD
```

## WCAG or Vendor Guidance (optional)

* [axe-core 3.4 - Heading levels should only increase by one](https://dequeuniversity.com/rules/axe/3.4/heading-order)

## Screenshots

![Screen Shot 2020-08-20 at 11 50 56 AM](https://user-images.githubusercontent.com/57469/90794936-706b0b00-e2db-11ea-85c2-27b376d283d4.png)

![Screen Shot 2020-08-20 at 11 47 02 AM](https://user-images.githubusercontent.com/57469/90794532-e622a700-e2da-11ea-8916-850060f7e959.png)

**Comment by obliviga** [comment]
Hi @micahchiang, I can can change the default value for the `headingLevel` prop on the `SaveInProgressIntro` component to be `2`, instead of `3`. That way, other teams that use this component can omit the prop on their end, so that their applications meet the acceptance criteria of this ticket. Here's the PR: https://github.com/department-of-veterans-affairs/vets-website/pull/21545

**Comment by obliviga** [comment]
Merged the PR, awaiting deploy.
