### ISSUE TITLE
sitewide, forms - 508-defect-2 [KEYBOARD]: Profile 2.0 - Focus MUST be managed when users switch from the read-only to edit in place UI

### ISSUE THREAD

**Issue by 1Copenut** [department-of-veterans-affairs/va-forms-system-core#446]
# [508-defect-2](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

```diff
! Team affected: vsa-authenticated-xp; Project: Profile 2.0
```

**Feedback framework**

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Description

Each of the profile "buckets" of information include an Edit button that lets users edit in place. When users click "Edit", focus is lost to the `<body>` tag. Modern browsers like Chrome and Firefox remember where focus was before it was lost, but IE11 forgets and moves focus to the end of the document. This forces IE users to `SHIFT + TAB` back through the document to edit their content. Screenshot attached below shows the moment when focus is lost.

## Related Issues
* https://github.com/department-of-veterans-affairs/va.gov-team/issues/4613 **(blocks this issue)**

## Point of Contact

**VFS Point of Contact:** _Jennifer, Trevor_

## Acceptance Criteria

- [ ] Focus is moved to the first native focusable element when users press "Edit"
- [ ] Focus is returned to the "Edit" button when users update or cancel their edit in place

## WCAG or Vendor Guidance (optional)

* [Focus Order: Understanding SC 2.4.3](https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-order.html)

## Screenshots or Trace Logs

![Screen Shot 2020-08-03 at 3 18 22 PM](https://user-images.githubusercontent.com/934879/89224927-f595b680-d59e-11ea-9d42-23a83a65de79.png)

**Comment by 1Copenut** [comment]
I'm no longer with Ad Hoc, but I can say this issue affects IE11 the worst, but it has a negative effect on the UX for most if not all keyboard and screen reader users. Browsers do their best to "remember" where focus was in the source order when nodes are removed, but screen readers won't announce that change until users take an action. Deliberately managing focus ensures assistive technologies pick up the change and keyboard users don't have to press `Tab` extra times.

**Comment by andaleliz** [comment]
@1copenut thank you for visiting us even though you're no longer with Ad Hoc! We miss you.

@obliviga the contact page, direct deposit page, and personal information page in profile all have modes that go from read to edit view via the edit button.  I'm not sure which environment you're checking this in, but you basically need to log into the site, and navigate to profile. A link to profile is available via the user name drop down menu in the main navigation, or from the "Go to profile" on My VA.

Once you get there, all of the sections I mentioned are available from the profile menu.

**Comment by obliviga** [comment]
Verified that this issue has been resolved in Staging:
https://images.zenhubusercontent.com/375815514/70bf1dd8-42c9-4fc4-b7e1-cf7eb0546318/staging_review_edit_button.mov
