### ISSUE TITLE
Demo Burial Form: Required error message does not display for Page 5

### ISSUE THREAD

**Issue by obliviga** [department-of-veterans-affairs/va-forms-system-core#479]
There are a few potential bugs that I noticed when reviewing the demo burial form:

- ~~Filling out Step 5, then activating the “No” radio button erases all of the inputted contents of that form
https://images.zenhubusercontent.com/375815514/3d549631-ab16-4215-83d5-75d7c1d78467/step_5_persist_inputted_data.mov~~ - KT: Discuss with the team. I think this is OK as is; it matches how the current production form works.
----------------------------------------------------
- Clicking Next during Step 5 does not do anything. Maybe it should inform the user that an input field is invalid
https://images.zenhubusercontent.com/375815514/2d993ea7-1693-4a6c-aa8f-8c8103aba5cb/step_5_next_button_dysfunctional.mov - KT: Looks like the required field error message is not displaying when Next is chosen on this page.
- Make this fix directly on vets-website if it is specific to the demo form.
-----------------------------------------------------
- ~~The user is allowed to put non-number characters for the `Amount of government or employer contribution. (*Required)` input field. I don’t think the user should be allowed to do this, because then on the review page, the output can potentially look incorrect:~~ - KT: I agree with this. This field should be restricted to numeric input only.  - AK: I've created a separate ticket for this here: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/484
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/153cc807-af2e-411b-bfd9-ca31bc2bed8d)

**Comment by bjmccotter7192** [comment]
VAFSC PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/530

**Comment by bjmccotter7192** [comment]
Vets-Website PR: https://github.com/department-of-veterans-affairs/vets-website/pull/21898
