### ISSUE TITLE
Add TTY to Telephone Component in VAFSC

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/va-forms-system-core#487]
## Task Description
This task is to use the new feature of the component-library `Telephone` web-component (TTY) and to be able to pass that option through the vafsc Telephone component.

## Considerations
- [DSVA Slack Thread for Telephone TTY](https://dsva.slack.com/archives/CE4304QPK/p1659031802724049)
:mega: The Design System team just made an update to the telephone web component which adds a new tty prop for indicating if the number is a TTY number or not. This follows our guidance on TTY being part of the aria-label and clickable link text.
If the component is used like this:
`<va-telephone tty contact="711" />`
The following markup will be rendered inside of the component:
`<a href="tel:711" aria-label="TTY. 7 1 1.">TTY: 711</a>`

## Acceptance Criteria
- [ ] Should be able to pass TTY to telephone component

**Comment by micahchiang** [comment]
Closing because we can use the web component directly
