### ISSUE TITLE
'simple-form' example checkbox doesn't update checked values.

### ISSUE THREAD

**Issue by adamwhitlock1** [department-of-veterans-affairs/va-forms-system-core#494]
**Description:**

When opening up the example `simple-form` and selecting checkbox values, those values don't update to `true` in the debug readout, and the required validation error message remains no matter how many values are checked.

Expected: checkbox values update the validation state and form data debug display
Actual: checking a checkbox doesn't change state of form values and validation error remains

Using version: 0.0.6 on MacOS Monterey 12.4, Chrome 103.0.5060.114

**Steps to reproduce:**

- Edit `examples/index.jsx` to import and use SimpleApp from 'simple-form/index.jsx`
- Run yarn serve-examples and open localhost:3000
- Check a checkbox and observe validation message and debug readout

**Comment by taylorkaren** [comment]
Notes from 8/9/22 walkthrough meeting with Adam:
- Adam: Is it the checkbox group, or something specific to how the form is wired up?
- Micah: We can double check to make sure things are put together properly.
- Adam: No immediate need for checkboxes, but will likely be using a radio group.
- BJ: On the demo burial form, the check box group does not have the required tag inside each option anymore. That’s the one difference he sees right now between the demo form and the simple form.

**Comment by taylorkaren** [comment]
Anish: Should check if the radio input is also experiencing the same error as the checkbox.

**Comment by bjmccotter7192** [comment]
[PR #539 ](https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/539)
