### ISSUE TITLE
508-defect-2: List loop patterns fail to manage focus and are missing descriptive labels and headings

### ISSUE THREAD

**Issue by joshkimux** [department-of-veterans-affairs/va-forms-system-core#507]
# [508-defect-2: List loop patterns fail to manage focus and are missing descriptive labels and headings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/platform/accessibility/guidance/defect-severity-rubric.md#508-defect-2)

## Feedback framework

- **❗️ Must** for if the feedback must be applied 
- **⚠️ Should** if the feedback is best practice 
- **✔️ Consider** for suggestions/enhancements 

## Definition of done

1. Review and acknowledge feedback.
1. Fix and/or document decisions made.
1. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

## Point of Contact

**VFS Point of Contact:** Josh

## User Story or Problem Statement

As a screen reader and keyboard user, I expect focus to be managed when interacting with dynamic fields that appear and disappear on the page.

## Details

Currently the list loop pattern fails to manage focus in several forms when:
- Another card is added. Focus is not managed and remains on the add another [x] button.
- A card is removed. Focus is lost.
- A card is updated. Focus is lost.
- A card is edited. Focus is sent to the h1.

Some list loops also have...
- Inconsistent headings; some cards have headings, others don't
- Duplicative button and field labels; screen reader users can get lost in duplicative, non-descriptive labels

## Acceptance Criteria

The following issues are remedied...
- [x] Focus is sent to the first new field when "Add [x]" is clicked
- [x] Focus is returned to the "Add another [x]" button when the remove button is clicked
- [x] Focus is sent to the first field being edited when "Edit" is clicked
- [x] Focus is returned to "Edit" when "Update" is clicked
- [ ] Input fields are uniquely labelled (being tracked [here](https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/525))
- [x] Headings are logically ordered

In the following forms:
- [ ] Burials, adding names
- [ ] Burials, adding service periods
- [ ] CoE, adding service periods
- [ ] CoE, listing all VA-backed loans

## Steps to Recreate

1. [Go to the "other name" page on step 3](https://www.va.gov/burials-and-memorials/application/530/military-history/service-periods)
2. Click "yes"
3. Fill in the fields and use `space` to click "Add another name"
4. Confirm focus remains on the add another name button
5. Shift tab to remove and click using `space`
6. Confirm focus is not sent back to the add another name button
7. Tab to add another name and click using `space`
8. Shift tab back to edit and click using `space`
9. Confirm focus is not sent to the first field
10. Tab to the update button and click using `space`
11. Confirm focus is not sent back to the `edit` field

## Related issues
There's an [ongoing issue with consistency of headings, descriptive button labels, and more across list loop patterns as documented in this ticket](https://github.com/department-of-veterans-affairs/va.gov-team/issues/43305).

### Adding names in the burials flow
https://user-images.githubusercontent.com/14154792/175342508-622c16ab-c66b-4aa9-bb3f-202058077e46.mov

### Service history in CoE
https://user-images.githubusercontent.com/14154792/182454877-02710788-e37e-4428-a1b8-ff7d735af299.MP4

- 0:05, legend "Service Start Date" is not announced
- 0:16, legend "Service End Date" is not announced
- 0:32, focus is lost (it should be sent to the first input field) 
- 0:40, "Please enter a date" is announced, but focus is sent to the first error on the page "Branch of Service"
- 1:04, Inline character by character validation announces despite the user not completing the field
- 1:37, "Error end of service must be after start of service" is announced even though the user has only input the month
- 1:50, Inline character by character validation announces despite the user not completing the field
- 2:28, No unique labels for "Edit" buttons 

https://user-images.githubusercontent.com/14154792/182456465-4209811d-ec6d-4b09-afa5-061b6be13b04.MP4

Errors persist after removing and adding a new service period

### Headings are inconsistent

<img width="885" alt="Screen Shot 2022-06-23 at 2 24 54 PM" src="https://user-images.githubusercontent.com/14154792/175368780-17b34c48-7d57-4f9c-883b-1757e4bad154.png">

### Navigating by form controls is ineffective with non-descriptive labels
<img width="559" alt="Screen Shot 2022-06-23 at 2 35 23 PM" src="https://user-images.githubusercontent.com/14154792/175371332-3ead8b46-6a73-4572-a1f9-b301c30b4600.png">

## Recommendation
- This is an issue that should be addressed as a design/content/IA challenge instead of an engineering one
- [Ryan Thurlwell created mockups of what a modified one thing per page version of this pattern could look like](https://www.sketch.com/s/92b41945-e57a-4eaa-9c66-ea017551f466/a/zxW8JYy)

## Folks who might be able to help push this forward or should have awareness
- @Mottie 
- @humancompanion-usds and @GnatalieH 
- @obliviga and @micahchiang 
- @davidakennedy and @TiffanyPender

**Comment by humancompanion-usds** [comment]
@joshkimux - Pam and I connected again today on using One Thing per Page in Supplemental Claims and as an improvement on our List and Loop in that application as well. Pam also brought her designs to CollabCycle Office Hours and got feedback. It would be good if you could help ensure the focus issues in this ticket are addressed should that design move forward (and I suspect you may already be doing that). From a Design System perspective, I would love for Pam, Robin, and yourself if you are interested, to come to Design System Council with the results of what is found in research on this work. The Supplemental Claims work has some urgency due to PACT Act passing and thus we may have this information sooner rather than later. At that point we could update List and Loop in the Design System to reflect an alternative variation and push teams in that direction.

All that said, the Service Date issues are not going to be solved by a revamp of List and Loop. Those seem like bugs in the way we've implemented that group of fields. We could address some of these issues by updating our guidance. Can you (either in this bug or via a meeting to discuss) help us understand what the correct implementation should be? Or is that something you can work with @obliviga on? Questions I have are:

* Is this a place to use fieldset to group Service Dates?
* Should "Service start date" and "Service end date" be labels or headers? 
  * If headers, which level and how to indicate that the group of fields are required? 
  * If labels, how to fix the header hierarchy?

**Comment by joshkimux** [comment]
I would love to come with Pam and Robin to the design system council once we conduct research ⭐ 

I'm working with @obliviga on this right now to see what we can fix at the moment. Would be more than happy to write in what the correct implementation should be too while we work on it 😄 

To answer your questions:

## Is this a place to use fieldset to group Service Dates?
It may depend on if we're talking about current vs experimental vs future state. For example:

### A bandaid'ed current state
If we were to remediate the existing pattern in the code (without design changes), we could use a combination of headings and legends. Sometime last year I think I tested it and it worked OK on VoiceOver iOS, but needs further testing on JAWS and NVDA. [Here's the "remediated" bandaid I wrote up to test (codepen). ](https://codepen.io/joshkimux/pen/porJZoE) 

Another thing we may want to consider in a bandaid state is limiting the user to editing only one card at a time to prevent a hypothetically unlimited amount of "Edit x" cards and simplify the issues related to unique headings.

That being said, it wouldn't be great. 

> Fieldsets can be nested if desired, although this can lead to confusion if overdone.
[W3C H82: Grouping form controls with FIELDSET and LEGEND ](https://www.w3.org/TR/2008/WD-WCAG20-TECHS-20080430/H82.html)

> It is possible to nest one fieldset element inside another, but it is not recommended. Screen readers do not automatically indicate the end of the fieldset element, so it is impossible for screen reader users to confidently know which fields belong within which fieldset.
[Gov.uk Using the fieldset and legend elements](https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/ )

### An experimental state (Pam and Robin's pattern)
Arguably, if only _one_ service period can be entered at any given time, we don't need to have nested fieldsets like in the previous example. As there could never be duplicates on the page at any given time (for example, there wouldn't be multiple service start date fieldsets because only one can be entered on the page).

```html
<h1>Form title</h1>
<h2>Step x of y</h2>
<h3>Add a new service period</h3>
<fieldset>
  <legend>
    Service start date
  </legend>
  <date component here>
</fieldset>
<fieldset>
  <legend>
    Service end date
  </legend>
  <date component here>
</fieldset>
```

### A future state (true one thing per page)
Ideally in the future though, we could explore having the `h3` (which tends to be the actual unique question on most pages) as the `h1` and bump the form title and stepper (we could delete this too for shorter forms possibly) into a separate landmark or section (like gov.uk).

```html
<h1>Add a new service period</h1> <!-- The h1 is a unique question -->
<fieldset>
  <legend>
    Service start date
  </legend>
  <date component here>
</fieldset>
<fieldset>
  <legend>
    Service end date
  </legend>
  <date component here>
</fieldset>


## Should "Service start date" and "Service end date" be labels or headers? If headers, which level and how to indicate that the group of fields are required?
These should be `legend` s as they're labelling multiple input fields. They wouldn't be headings in this instance though as they're arguably not starting up a new section so much as they are grouping a couple of input fields together. The name of the card (e.g. "Add a new service period" or "Marine Corps", however, given that it's both starting the section (the card) and providing context to several input fields) should arguably be both a `legend` and a heading.

## If labels, how to fix the header hierarchy?
For the instances here, we just need to make sure that when a new card is created, it has a unique heading. The examples in this ticket are created, but don't get a unique heading (they stay just as legends) which creates an inconsistent experience. This isn't universal, however. I believe Robin fixed this in the 526 form 😄

**Comment by joshkimux** [comment]
I forgot to also mention, we never went about fixing this pattern for good because we got caught up with the complexity of a list loop _upload_ pattern where a user can upload multiple documents, name them, edit them, and delete them 😕 

Need to dig up the ticket that stumped me there so we can group them all into one mega ticket.

**Comment by obliviga** [comment]
Hi @joshkimux, do you know the URL to access the COE form? I was only able to find this one: https://www.va.gov/housing-assistance/home-loans/how-to-request-coe/

**Comment by jerekshoe** [comment]
https://staging.va.gov/housing-assistance/home-loans/request-coe-form-26-1880

**Comment by jerekshoe** [comment]
It’s not live on prod yet

**Comment by obliviga** [comment]
@jerekshoe, just what I needed. Thank you!

**Comment by humancompanion-usds** [comment]
Doh! ```<legend>``` I knew I was missing something yesterday. Thanks for your detailed response @joshkimux! Much appreciated. 

Some more questions:

1. We should be able to quickly update the [Service Dates pattern](https://design.va.gov/patterns/forms/service-history) to show the fieldset code structure Josh provided. 
2. I'd be for showing the proposed future state as well and marking the pattern "Use with caution", as that seems to be true here given this entire issue. That would clue folks into the decisions to be made when implementing this pattern.
3. @k80bowman and @bkjohnson - How do you feel about us creating a va-service-date or va-service-dates component that would codify this? This is, in my mind at least, a pretty good example of something that is specific to VA that in future would leverage the components of the USWDS and put them into a pattern that is likely used in many places throughout our applications. Worth discussing at stand-up today.

**Comment by joshkimux** [comment]
Small note here. I asked Robin if he had any more research around the service dates pattern and he [pulled up these findings](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/ebenefits/apply-for-home-loan-COE/research-design/usability-testing-2/research-findings.md#details-of-findings).

Given that some work may be done on this pattern, I was wondering if we might be able to dig a little deeper into how it's performing for Veterans from an experience (and not just an interaction) perspective.
- Are service dates memorable or easily findable? If not, why? Is the day field required?
- Are there other known unknowns around how this pattern is performing? For example, I wasn't aware of the issue brought up by this Veteran on service dates

> One participants had 2 service history periods separated by a 2 month period and wasn't sure how to enter them.

**Comment by bkjohnson** [comment]
@humancompanion-usds There might be something I'm missing here (I've only skimmed the previous comments), but I think it might make more sense to have something more generalized, like `<va-date-range type="Service" start="2000-01-01" end="2010-01-01" />`.

**Comment by humancompanion-usds** [comment]
@bkjohnson - Let's discuss. What I'm arguing for is a [molecule](https://atomicdesign.bradfrost.com/chapter-2/#molecules) rather than an atom. The nearest analogy in our system might be to the [Search input](https://design.va.gov/components/search-input#with-type-ahead). The text input, button, etc. all combine to form a more robust component that solves for a specific interaction (type ahead). 

If there are other date range types that we are already aware of then a more generic component might make sense. If not, I'd rather solve for this very common problem so that teams can just pull this component off the shelf and know that Service Dates will be collected correctly.

@joshkimux - Yeah, we had the same problem collecting service dates on usajobs.gov. I was never fully satisfied with the solution we came up with in Profile. It had the added complexity of having to allow for a future/to-be-determined release date. Our admittedly "meh" solution to the break in service was to add hint text: 

> If you have a break in service, please add your additional service dates.

Any time you have to explain the interface it's a red flag, but I'm not sure what else to suggest. Here's what it looks like:
![Screen Shot 2022-08-04 at 11 20 45 AM](https://user-images.githubusercontent.com/52176351/182888340-67d16ff3-9128-4e3e-bafe-a8bb1918c4c9.png)

**Comment by k80bowman** [comment]
@humancompanion-usds @bkjohnson I think creating a component for this is a great idea. I can add it to our list. As for the question of creating something more general vs. something more specific, it seems to me that if we do have other types of date range inputs, we would want them all to look/function the same way. I don't think we lose anything by creating something more general that can be applied to service dates.

**Comment by bkjohnson** [comment]
> If there are other date range types that we are already aware of then a more generic component might make sense. 

@humancompanion-usds There's a date range for:

- [high school education](https://github.com/department-of-veterans-affairs/vets-website/blob/30f1654bab6d4d15325545f382309b8a8e53e83f/src/applications/edu-benefits/5490/config/form.js#L657)
- [post-high school education](https://github.com/department-of-veterans-affairs/vets-website/blob/30f1654bab6d4d15325545f382309b8a8e53e83f/src/applications/edu-benefits/definitions/postHighSchoolTrainings.js#L28)
- [treatment dates](https://github.com/department-of-veterans-affairs/vets-website/blob/30f1654bab6d4d15325545f382309b8a8e53e83f/src/applications/appeals/995/pages/evidencePrivateRecords.js#L54-L58)
- [time spent as a POW](https://github.com/department-of-veterans-affairs/vets-website/blob/993cb9561b56695fffddcc9eed5d8fba3d5420e3/src/applications/pensions/config/form.js#L487-L495)
- [job history](https://github.com/department-of-veterans-affairs/vets-website/blob/993cb9561b56695fffddcc9eed5d8fba3d5420e3/src/applications/pensions/config/form.js#L635)
- [unit assignment](https://github.com/department-of-veterans-affairs/vets-website/blob/993cb9561b56695fffddcc9eed5d8fba3d5420e3/src/applications/disability-benefits/all-claims/pages/incidentUnitAssignment.js#L25-L26)
- [loan history](https://github.com/department-of-veterans-affairs/vets-website/blob/993cb9561b56695fffddcc9eed5d8fba3d5420e3/src/applications/lgy/coe/form/config/chapters/loans/loanHistory.js#L56-L60)

And possibly more.

**Comment by Mottie** [comment]
After discussing this with @thehastingsp for the list-loop pattern in general, I think it might be better use a pattern that spans several pages.

```mermaid
flowchart TB
    sHx[Service history summary]
    sHx --> next[Next page]
    sHx -. add .-> addOrEdit[service period start & end] .-> sHx
    sHx -. edit .-> addOrEdit
    sHx -. delete .-> sHx
```

**Comment by humancompanion-usds** [comment]
@Mottie - Yes, I think we're all in agreement that List and Loop should incorporate One Thing per Page and step the user through several pages to ask the questions necessary. But one of those pages is going to capture Service Dates and this bug does touch on the problems in implementing that collection of data. 

@bkjohnson - That's a healthy list. One concern about having one component that spans all of those date ranges would be the validation, focus, and other behaviors (which this issue covers). If all of those rules are consistent across these date ranges, and ideally they would be, then I'm all for one component that can handle it. But I would start with Service Dates and the requirements to make that work and then see which date ranges, if any, vary from those requirements and behavior. Perhaps there is even a meta-type that a number of date ranges map to which share the same behavior. Much like we'd do a design audit to start a new component it is probably worth doing a development audit to dig into each of those date ranges.

**Comment by obliviga** [comment]
Hi @joshkimux, regarding the following bold red underlined text that is not a heading but should be:
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/0d26078e-fe81-49ce-857b-2d4e31e633e4)

I don't think this a forms library team issue, as engineers should be able to wrap the component that renders the full name with whatever HTML element they want.

And regarding the issue "Input fields are uniquely labelled", do you have a recommendation for how they should be labelled? Thank you!

**Comment by obliviga** [comment]
@joshkimux, I just merged the PR to address the focus related issues. You can test the fix here: http://095b28f803703b0d827044c637419180.review.vetsgov-internal/burials-and-memorials/application/530/military-history/previous-names

**Comment by joshkimux** [comment]
@obliviga this is great! Thanks so much!

> And regarding the issue "Input fields are uniquely labelled", do you have a recommendation for how they should be labelled? Thank you!

This is a tough one to answer. Here are the problems we need to address:
- Some list loop patterns allow users to add multiple generic `Add new [name of card e.g. service periods]` cards. This can create duplicative headings and fields as it will remain generic until added.
- _After_ adding multiple cards, they can be opened up simultaneously at the same time which creates multiple input fields with the same labels.
- In their non edited states, each card shares the same buttons for editing and deleting 

Ideally, the following could solve this problem (albeit as a crude bandaid):
- Only one new card can be added at any given time (solves the first issue)
- Only one card can be edited at any given time (solves the second issue) 
- Edit and delete buttons have `aria-labels` (e.g. Edit Marine Corps) based on the first heading within each card (which depends on the teams it seems like)

**Comment by obliviga** [comment]
@joshkimux, thank you so much for that update. I have created a separate ticket that will focus on addressing the input label problem: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/va-forms-system-core/525

Feel free to update that new ticket with any more information you find on this problem.
