### ISSUE TITLE
Pass a custom function when onChange is triggered for a component

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#531]
## Context
This comes from the 8/9/22 walkthrough session with Adam Whitlock ([notes page](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2297692175/Focused+Walkthrough+Session+2+Adam+Whitlock)).

Adam previously submitted a [PR](https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/497)  that added the ability to pass a custom function when onChange is triggered for the text field component.

This ticket is to look into passing a custom function when onChange is triggered for any component so that there is a way to do this in general for all components instead of addressing them one at a time.

## Task Description
- VAFSC form field components that use an onChange handler should be extended to accept a custom handler passed in as a prop in addition to the formik onChange handler. 

## Considerations
- [Custom onChange that was added to TextField](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/a9fa9b694f6f6a69de3582abedda77278f4de102/src/form-builder/TextField.tsx#L16-L19). Something similar can probably be used for the other fields.
- Components that need to be updated:
  - [SSN field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/666b77725f4b93cd991713a6f0bd9002bb147c98/src/form-builder/SSNField.tsx#L1)
  - [Select field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/ed8613727a8fc8a65559592e6fc6f448c19cb35e/src/form-builder/SelectField.tsx#L1)
  - [Radio group](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/09a8331d164949016a314fb9b11937bea58cf7e6/src/form-builder/RadioGroup.tsx#L1)
  - [Phone field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/666b77725f4b93cd991713a6f0bd9002bb147c98/src/form-builder/PhoneField.tsx#L1)
  - [Number field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/768e739a32a965e1f0b5e2aadb858a38f0e5d61e/src/form-builder/NumberField.tsx#L1)
  - [Email field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/666b77725f4b93cd991713a6f0bd9002bb147c98/src/form-builder/EmailField.tsx#L1)
  - [Date field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/0c0c0b15fddedd782954e87760893b3ca0999518/src/form-builder/DateField.tsx#L1)
  - [Checkbox field](https://github.com/department-of-veterans-affairs/va-forms-system-core/blob/5a87dc8dc5a46b2dbe6f925aa314ca6439764fd9/src/form-builder/CheckboxField.tsx#L1)

## Acceptance Criteria
- [ ] onChange prop support has been added to all of the components above
- [ ] PR has been merged into main

**Comment by harshil1793** [comment]
@micahchiang The email field is already using the TextField component so I believe we don't need to make any changes to Email field, right?
