### ISSUE TITLE
Fix: Add additional UI conditionals to formik initial values

### ISSUE THREAD

**Issue by harshil1793** [department-of-veterans-affairs/va-forms-system-core#570]
## Description
When the fields are not in schema formik doesn't register the field in initial values. Sometimes, there are data points (previously used in UI schema) that need to be used for the sole purpose of showing and hiding different fields. When these fields are not registered, formik doesn't hook into any validation functions for it. This needs to be added so formik registers it as an initial value.

This was a subject that was up for debate in a mob session, so solution will be laid out in a draft PR and can be discussed as a team.

## Consideration
- This can be reproduced for PreviousName Radio group

## Proposed solution
- Add-on values to be appended to bottom of schema data
- [DRAFT PR](https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/594)

## Why this approach? 
- Harshill - will help transform the data at time of submission - instead of having to look for it, you have an object in your application that already identifies it. 

## Acceptance Criteria
- [ ] Solution to adding UI data is agreed upon and merged

**Comment by mlauren** [comment]
hi @harshil1793 I am seeing the values persist here: 
![Screen Shot 2022-08-24 at 3.42.34 PM.png](https://images.zenhubusercontent.com/622a528977968ea0007000f0/4a9ee746-7b4e-4b1c-968f-a3c3c15e33b0)
Do you have steps to reproduce, or its possible the work @bjmccotter7192 addressed this? Thanks
