### ISSUE TITLE
[THE LAST TICKET] Remove FLT code owner permissions

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/va-forms-system-core#571]
## Task Description
Remove FLT members from code owners on:
- These vets-website directories: [forms](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/platform/forms) and [forms-system](https://github.com/department-of-veterans-affairs/vets-website/tree/main/src/platform/forms-system).
- The [vets-json-schema repo](https://github.com/department-of-veterans-affairs/vets-json-schema).
- The [va-forms-system-core repo](https://github.com/department-of-veterans-affairs/va-forms-system-core).

- And take the FLT group out of the va-forms-system core repo membership!

## Acceptance Criteria
- [x] FLT members are no longer code owners in the directories and repos listed above.
- [x] FLT members are no longer members of the va-forms-system core repo.

**Comment by bjmccotter7192** [comment]
~~VAFSC Code Owner Removal: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/621~~ "MERGED"

~~Vets-json-schema Code Owner Removal: https://github.com/department-of-veterans-affairs/vets-json-schema/pull/719~~ "MERGED"

~~Vets-website Code Owner Removal: https://github.com/department-of-veterans-affairs/vets-website/pull/22157~~ "MERGED"

**Comment by bjmccotter7192** [comment]
@k80bowman Adding you so at the end of the day you can remove our team from the repo :(

**Comment by bjmccotter7192** [comment]
All repos have been updated and merged to NOT include PST-FLT in codeowners files

**Comment by k80bowman** [comment]
Thank you @bjmccotter7192! PST-forms-system-core has been removed from the va-forms-system-core repo, so I'm going to close this out.
