### ISSUE TITLE
Burial Demo Form: Investigate DateField component validation bug

### ISSUE THREAD

**Issue by obliviga** [department-of-veterans-affairs/va-forms-system-core#595]
There is a bug on the burial form demo that allows the user to continue with the next steps even if they have provided an empty value in one of the date fields.

Example:
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/1ba3d5f5-e24e-4722-9fec-d4b3bdd1c1ba)

In the above screenshot, the DateField should be marked as invalid because no value was supplied to the Day field.

**Acceptance Criteria**
- [x] Ensure that the DateField is invalid if any field within the component is blank

**Comment by nickjg231** [comment]
PR: https://github.com/department-of-veterans-affairs/va-forms-system-core/pull/604
