### ISSUE TITLE
DateField component error messaging is not behaving as expected

### ISSUE THREAD

**Issue by obliviga** [department-of-veterans-affairs/va-forms-system-core#607]
### Problem
In our Burial Demo, if the user inputs a blank day for the date, no error shows up:
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/9ee3dd39-0b85-4f03-bc2f-ca7cbf234db0)

### Steps to Reproduce
1. http://localhost:3002/veteran-information
2. Scroll down to the Date component and enter the month and year
3. Leave the day field blank
4. Press the Continue button and notice how no error appears

### Expectations
I expect an inline error message to appear for a required date input if the user leaves one of the date fields blank.

### Acceptance Criteria
- [ ] Ensure that the user is not allowed to continue with the form when a **required** date field is left blank
- [ ] Ensure that the date field is accompanied with an error message if one of its fields are left blank

**Comment by taylorkaren** [comment]
This looks like the same issue as was reported on ticket #595. @obliviga, can you please talk to @nickjg231 about this (he worked on ticket #595) and determine if this is still an issue or not?
