### ISSUE TITLE
Clarifying the base

### ISSUE THREAD

**Issue by mgifford** [department-of-veterans-affairs/va-forms-system-core#619]
Is the form system a:
"VA Forms System Core is just a light layer on top of Formik"
https://department-of-veterans-affairs.github.io/va-forms-system-core/tutorials/getting-started.html

or is it according to the Readme:
"VA Forms System Core (VAFSC) is the second generation of the forms library which is built using React, Formik, and Typescript."

Maybe the website is just out of date.

**Comment by taylorkaren** [comment]
Let's update the text on the https://department-of-veterans-affairs.github.io/va-forms-system-core/tutorials/getting-started.html page to match what's in the ReadMe: "VA Forms System Core (VAFSC) is the second generation of the forms library which is built using React, Formik, and Typescript."
