### ISSUE TITLE
Status of Formik

### ISSUE THREAD

**Issue by mgifford** [department-of-veterans-affairs/va-forms-system-core#620]
Should the VA contribute to Formik, fork the code or move on to React Hook Form as is suggested here:
https://github.com/jaredpalmer/formik/discussions/3526

There are no security issues with it yet, but this is just a matter of time.

**Comment by taylorkaren** [comment]
Work on the new VA Forms System Core (VAFSC) is still in the developmental stage and will be pausing as of today (9/9/22). These questions will be addressed if and when development is resumed.
