### ISSUE TITLE
508-defect-2 [KEYBOARD]: Focus should be restored to the Add Another button when users press Remove when editing in place

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/va-forms-system-core#89]
## Description
[Original DST ticket](https://app.zenhub.com/workspaces/vsp-design-system-5f8de67192551b0012ebb802/issues/department-of-veterans-affairs/va.gov-team/13007) (Opened 8/28/20)

Focus is not being returned to the Add Another button when users press Remove on the Review > edit in place UI. See original ticket for screen shot. 

## Steps to recreate
- Enter staging.va.gov/view-change-dependents/add-remove-form686c/
- Check two or three dependent situations, including adding and removing at least one dependent each
- Navigate to the review page and open the accordions
- Click "edit" to enter inline editing mode, add a dependent, then click the "Remove" button after the generic card appears to add a dependent.
- Verify that focus is not returned to the Add Another button

## Definition of done
1. Review and acknowledge feedback
2. Fix and/or document decisions made
3. Accessibility specialist will close ticket after reviewing documented decisions / validating fix.

**Comment by taylorkaren** [comment]
Plan to do a mob session on this.

**Comment by taylorkaren** [comment]
Mob session notes: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2061467674/Mob+Session+1+20+2022.

**Comment by ken-non** [comment]
@sdk-irl to work on this week.

**Comment by obliviga** [comment]
Hi @micahchiang, do you know of a VA account where this view will populate? I tried a couple of accounts but none of the accounts I've tried have dependents:
![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/cdb5bf24-9b87-41d9-9dbb-7d80465b8ffd)

**Comment by obliviga** [comment]
Hi @micahchiang, I tried the two user accounts you suggested but I am getting the same "no depends" message for the first account. I'm getting the following error for the second account: ![image.png](https://images.zenhubusercontent.com/6283eaffdea4c21364d67e5a/da2b9355-59c3-40c1-bbe7-ec2d23afcd38)

@1Copenut, would you have test credentials that have dependents associated with it? Thank you!

**Comment by taylorkaren** [comment]
@obliviga: Trevor Pierce (aka 1Copenut) is no longer at VA.

**Comment by obliviga** [comment]
This fix has been deployed here: http://0ee417b1ce5b4e3de6622e74300fa3e0.review.vetsgov-internal/view-change-dependents/add-remove-form686c/

Since we can only test this fix locally, I'm going to close this ticket as the code has been merged into the main branch.
